spring:
  application:
    name: dockerizing-test
  datasource:
    url: ${DB_URL} # jdbc:postgresql://localhost:5432/railway-test-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

server:
  servlet:
    context-path: /api